config/routes.rb
Rails.application.routes.draw do

  root "products#index"

  # admin

    # adminコントローラ
      get 'admin' =>'admins#index'

    # admin_endusersコントローラ
      get "admins/users" => "admin_endusers#index"
      get "admins/users/:id" => "admin_endusers#show", as: "admins_user"
      get "admins/users/:id/edit" => "admin_endusers#edit", as: "admins_users_edit"
      patch "admins/users/:id" => "admin_endusers#update", as: "admins_users_update"
      delete "admins/users/:id" => "admin_endusers#destroy", as:"admins_users_destroy"

    # admin_productsコントローラ
      get "admins/products/new" => "admin_products#new"
      get "admins/products" => "admin_products#index"
      get "admins/products/:id" => "admin_products#show", as: "admins_product"
      post "admins/products/new" => "admin_products#create", as: "admins_product_create"
      get "admins/products/:id/edit" => "admin_products#edit", as: "admins_products_edit"
      patch "admins/products/:id" => "admin_products#update",as: "admins_products_update"
      put "admins/products/:id" => "admin_products#update"
      delete "admins/products/:id" => "admin_products#destroy"

    # admin_inquiriesコントローラ
      get "admins/inquiries" => "admin_inquiries#index"
      get "admins/inquiries/:id" => "admin_inquiries#show", as: "admins_inquiry"
      # post "admins/inquiries/:id" => "admin_inquiries#create"
      patch "admins/inquiries/:id" => "admin_inquiries#create"

    # admin_reviewsコントローラ
      get "admins/reviews/:id/edit" => "admin_reviews#edit", as: "admins_review_edit"
      patch "admins/reviews/:id" => "admin_reviews#update", as: "admins_review_update"
      put "admins/reviews/:id" => "admin_reviews#update"
      delete "admins/reviews/:id" => "admin_reviews#destroy", as: "admins_review_destroy"

    # admin_order_historiesコントローラ
      get "admins/order_histories" => "admin_order_histories#index"
      get "admins/order_histories/:id" => "admin_order_histories#show", as: "admins_order_history"
      patch "admins/order_histories/:id" => "admin_order_histories#update", as: "admins_order_history_update"
      put "admins/order_histories/:id" => "admin_order_histories#update"

    # admin_arrival_recordsコントローラ
      get "admins/arrival_records" => "admin_arrival_records#index"
      get "admins/:id/arrival_records/new" => "admin_arrival_records#new", as: "admins_arrival_records_new"
      post "admins/:id/arrival_records" => "admin_arrival_records#create", as: "admins_arrival_records_create"

    # admin devise
      devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }


  # end_users

    # usersコントローラ
      get "users/close" => "users#complete"
      get "users/:id" => "users#show", as: "user"
      get "users/:id/edit" => "users#edit",as: "users_edit"
      get "users/:id/close" => "users#close",as: "user_close"
      patch "users/:id" => "users#update",as:"user_update"
      put "users/:id" => "users#update"
      delete "users/:id/destroy" => "users#destroy",as: "destroy_user"

    # user_reviewsコントローラ
      get "product/:id/user_reviews" => "user_reviews#index", as: "product_reviews"
      post "products/:id" => "user_reviews#create"

    # productsコントローラ
      get "products/search" => "products#search"
      resources :products, only:[:show,:create]


    # user_inquiriesコントローラ
      get "user/:id/inquiries/complete" => "user_inquiries#complete", as: "user_inquiries_complete"
      get "user/:id/inquiries/new" => "user_inquiries#new", as: "new_user_inquiry"
      post "user/:id/inquiries" => "user_inquiries#create", as: "user_inquiries"

    # user_cartsコントローラ

      get "carts" => "user_carts#index", as: "user_carts"
      patch "carts/:id" => "user_carts#update",as: "user_carts_update"
      put "carts/:id" => "user_carts#update"
      delete "carts/:id" => "user_carts#destroy",as: "user_carts_delete"
      post "carts/:id" => "user_carts#create" ,as: "user_carts_create"

    # user_purchasesコントローラ
      get "users/:id/purchase/new" => "user_purchases#new", as: "user_purchases_new"
      post "users/:id/purchase" => "user_purchases#create", as: "user_purchases_create"
      get "users/purchase/complete" => "user_purchases#complete"

    # user_addressesコントローラ
      get "users/:id/user_addresses" => "user_addresses#show", as: "user_address"
      get "users/:id/user_addresses/new" => "user_addresses#new", as: "user_addresses_new"
      post "users/:id/user_addresses/new" => "user_addresses#create", as:"user_address_create"
      get "users/:id/user_addresses/edit" => "user_addresses#edit", as: "user_addresses_edit"
      patch "users/:id/user_addresses" => "user_addresses#update", as: "user_addresses_update"
      put "users/:id/user_addresses" => "user_addresses#update"
      delete "users/:id" => "user_addresses#destroy",as: "user_address_destroy" #userのshowページ

    # user_order_historiesコントローラ
      get "users/user_order_histories/:id" => "user_order_histories#show", as: "user_order_history"


    # user_favoritesコントローラ
      post "users/:id/favorites" => "user_favorites#create", as: "user_favorites_create"
      delete "users/:id/favorites" => "user_favorites#destroy", as: "user_favorites_destroy"

    # user_genresコントローラー
      get "/genres/:id" => "user_genres#show", as: "user_genre"

    #end_user devise
      devise_for :end_users, controllers: {
      sessions:      'users/sessions',
      passwords:     'users/passwords',
      registrations: 'users/registrations'
    }





end

app/controllers/admin_products_controller.rb
class AdminProductsController < ApplicationController

before_action :authenticate_admin!, only:[:index, :show, :new, :create, :edit, :update, :destroy]

def index
	@products = Product.page(params[:page]).per(30)
end


def show
	@product = Product.find(params[:id])
	@reviews = Review.where(product_id:@product.id).page(params[:page]).per(5)
	@arrival_stocks = @product.arrival_records.all.sum(:arrival_product)
	@history_stocks = @product.product_histories.all.sum(:order_quantity)
	@stocks = @arrival_stocks - @history_stocks
	@new_products = Product.page(params[:page])
end


	def new
		@admin_product = Product.new
		@artist = Artist.new
		@label = Label.new
		@genre = Genre.new
		@disc = @admin_product.discs.build
		@disc.songs.build

	end

	def create
		@artist = Artist.new(artist_params)
		unless Artist.find_by(name:@artist.name)
			@artist.save
		end
		@label = Label.new(label_params)
		unless Label.find_by(name:@label.name)
			@label.save
		end
		@genre = Genre.new(genre_params)
		unless Genre.find_by(name:@genre.name)
			@genre.save
		end

		@admin_product = Product.new(product_params)
		@admin_product.artist_id = Artist.find_by(name:@artist.name).id
		@admin_product.label_id = Label.find_by(name:@label.name).id
		@admin_product.genre_id =  Genre.find_by(name:@genre.name).id


		  if @admin_product.save
		    redirect_to admins_arrival_records_new_path(@admin_product.id)
		  else
		    flash.now[:danger] = "商品登録に失敗しました"
		    render :new
		  end
	end


	def edit
		@admin_product = Product.find(params[:id])
		@artist = @admin_product.artist
    @label = @admin_product.label
    @genre = @admin_product.genre
	end

	def update
		admin_product = Product.find(params[:id])

		artist = Artist.find_or_create_by(name:params[:artist][:name])

		unless admin_product.artist.name == artist.name
	     artist = Artist.new(artist_params)
			 artist.save
			 admin_product.artist_id = artist.id
		end

		label = Label.find_or_create_by(name:params[:label][:name])
		unless admin_product.label.name == label.name
		  label = Label.new(label_params)
		  label.save
		  admin_product.label_id = label.id
		end

	  genre = Genre.find_or_create_by(name:params[:genre][:name])
		unless admin_product.genre.name == genre.name
		  genre = Genre.new(genre_params)
		  genre.save
		  admin_product.genre_id = genre.id
		end

		admin_product.update(product_params)
		redirect_to admins_product_path(admin_product.id)
	end



def destroy
	@admin_product = Product.find(params[:id])
	@artist = @admin_product.artist
    @label = @admin_product.label
    @genre = @admin_product.genre
	 if @admin_product.destroy
	    flash[:success] = "商品を削除しました"
	    redirect_to admins_products_path
	 else
	    flash.now[:danger] = "商品削除に失敗しました"
	    render :edit
	 end

end


	private
		def product_params
			params.require(:product).permit(:title,:price,:release_date,:product_image, :sale_status,
			  discs_attributes: [:id, :disc_num, :_destroy, :created_at, :updated_at,
			  songs_attributes: [:id, :song_num, :name, :_destroy, :created_at, :updated_at]])
		end

		def artist_params
			params.require(:artist).permit(:name)
		end

		def label_params
			params.require(:label).permit(:name)
		end

		def genre_params
			params.require(:genre).permit(:name)
		end


end

app/helpers/admin_products_helper.rb
module AdminProductsHelper
end

app/views/admin_products/_disc_fields.html.erb
<div class ="nested-fields">
<h5>ディスク</h5>

<%= f.number_field :disc_num ,required: true , min:1, :size => "50*24"%>

<div class="links">
  <%= link_to_add_association "曲を追加", f, :songs, class: "btn btn-info btn-xs" %>
</div>

<%= f.fields_for :songs do |song| %>
	<%=render "song_fields", :f => song%>
 <% end %>

</div>

app/views/admin_products/_song_fields.html.erb
<div class="nested-fields">
  <h5>ナンバー</h5>

	<%= f.number_field :song_num ,required: true , min:1, :size => "50*24" %>

	<h5>曲名</h5>
	<%= f.text_field :name ,required: true, :size => "50*24" %>
  <%= link_to_remove_association "曲を削除", f, class: "btn btn-danger btn-xs" %>
</div>

app/views/admin_products/edit.html.erb
<div class="container">
  <div class="row">
  	<div class="col-md-3"></div>
  	<div class="col-md-5">	
		<h1>登録商品編集</h1>
		<%= form_for @admin_product, url:admins_products_update_path do |f| %>
			<h4>商品名</h4>
			<%= f.text_field :title ,required: true, :size => "50*24" %>
			<h4>アーティスト</h4>
			  <%= fields_for @artist do |i| %>
				<%= i.text_field :name, list: 'artist' ,required: true, :size => "50*24" %>
				<datalist id="artist">
					<% Artist.all.each do |artist| %>
					<option value="<%= artist.name %>"></option>
					<% end %>
				</datalist>
			  <% end %>
			<h4>レーベル</h4>
			  <%= fields_for @label do |i| %>
				<%= i.text_field :name, list: 'label' ,required: true, :size => "50*24" %>
				<datalist id="label">
					<% Label.all.each do |label| %>
					<option value="<%= label.name %>"></option>
					<% end %>
				</datalist>
			  <% end %>
			<h4>ジャンル</h4>
			  <%= fields_for @genre do |i| %>
				<%= i.text_field :name, list: 'genre' ,required: true, :size => "50*24" %>
				<datalist id="genre">
					<% Genre.all.each do |genre| %>
					<option value="<%= genre.name %>"></option>
					<% end %>
				</datalist>
			  <% end %>
			<h4>ジャケット画像</h4>
			<%= attachment_image_tag @admin_product, :product_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %>
			<%= f.attachment_field :product_image %>
			<h4>価格(税込)</h4>
			<%= f.text_field :price ,required: true, :size => "50*24" %>
			<h4>発売日</h4>
			<%= f.date_field :release_date ,required: true, :size => "50*24" %>
			<h4>収録曲</h4>
			  <%= f.fields_for :discs do |disc| %>
			    <%=render "disc_fields",:f => disc%>
			  <% end %>
			  <div class="links">
				<%= link_to_add_association "ディスクを追加", f, :discs, class: "btn btn-info btn-xs"  %>
			  </div>
			<h4>販売ステータス</h4>
			<%= f.select :sale_status, Product.sale_statuses.keys.map {|k| [k, k]} %>
			<%=  f.submit "編集内容を保存する", class: "btn btn-success btn-block" %>
			<%= link_to "商品を削除する", admins_products_update_path(@admin_product), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger btn-block" %>
		<% end %>
  	</div>
  </div>	
</div>

app/views/admin_products/index.html.erb
<div class="col-sm-12">
  <div class = "products-box">
  	<h1 class = "product-head-title">登録商品一覧</h1>
		<table class="table table table-bordered table-striped orderhistroy-table">
		  <thead>
		    <tr>
		      <th scope="col">登録日時</th>
		      <th scope="col">商品ID</th>
		      <th scope="col">商品タイトル</th>
		      <th scope="col">商品画像</th>
		      <th scope="col">アーティスト</th>
		      <th scope="col">レーベル</th>
		      <th scope="col">ジャンル</th>
		      <th scope="col">価格（税込）</th>
		      <th scope="col">在庫数</th>
		      <th scope="col">ステータス</th>
		    </tr>
		  </thead>

		<% @products.each do |product| %>
		    <tr>
		      <td><span><%= product.created_at %></span></td>
		      <td><span><%= link_to"#{product.id}", admins_product_path(product.id) %></span></td>
		      <td><span><%= product.title %></span></td>
		      <td><span><%= attachment_image_tag product, :product_image,
		       fallback: "no_image.jpg", size: "50x50" %></span></td>
		      <td><span><%= product.artist.name %></span></td>
		      <td><span><%= product.label.name %></span></td>
		      <td><span><%= product.genre.name %></span></td>
		      <td><span><%= product.price %></span></td>
		      <% arrival_stocks = product.arrival_records.all.sum(:arrival_product) %>
		      <% history_stocks = product.product_histories.all.sum(:order_quantity) %>
		      <td><span><%= stock = arrival_stocks - history_stocks %></span></td>
		      <td>
		      	<% if stock == 0 %>
		      	  <span style="color: red;">在庫切れ </span>
		      	<% else %>
		      	  <span><%= product.sale_status %></span>
		      	<% end %>
		      </td>
		    </td>
		  <% end %>
        </table>
        <%= paginate @products %>
  </div>
</div>

 </div>
</div>

app/views/admin_products/new.html.erb
<div class="container">
  <div class="row">
  	<div class="col-md-3"></div>
  	<div class="col-md-5">	
		<h1>新規商品登録</h1>
		<%= form_for @admin_product, url: admins_product_create_path do |f| %>
		<%= render 'layouts/error_messages', model: f.object %>
			<h4>商品名</h4>
			<%= f.text_field :title ,required: true, :size => "50*24" %>
			<h4>アーティスト</h4>
			  <%= fields_for @artist do |i| %>
				<%= i.text_field :name, list: 'artist' ,required: true, :size => "50*24" %>
				<datalist id="artist">
					<% Artist.all.each do |artist| %>
					<option value="<%= artist.name %>"></option>
					<% end %>
				</datalist>
			  <% end %>
			<h4>レーベル</h4>
			  <%= fields_for @label do |i| %>
				<%= i.text_field :name, list: 'label' ,required: true, :size => "50*24" %>
				<datalist id="label">
					<% Label.all.each do |label| %>
					<option value="<%= label.name %>"></option>
					<% end %>
				</datalist>
			  <% end %>
			<h4>ジャンル</h4>
			  <%= fields_for @genre do |i| %>
				<%= i.text_field :name, list: 'genre' ,required: true, :size => "50*24" %>
				<datalist id="genre">
					<% Genre.all.each do |genre| %>
					<option value="<%= genre.name %>"></option>
					<% end %>
				</datalist>
			  <% end %>
			<h4>ジャケット画像</h4>
			<%= f.attachment_field :product_image %>
			<h4>価格(税込)</h4>
			<%= f.text_field :price ,required: true, :size => "50*24" %>
			<h4>発売日</h4>
			<%= f.date_field :release_date ,required: true, :size => "50*24" %>
			<h4>収録曲</h4>
			  <%= f.fields_for :discs do |disc| %>
			    <%=render "disc_fields",:f => disc%>
			  <% end %>
			  <div class="links">
				<%= link_to_add_association "ディスクを追加", f, :discs, class: "btn btn-info btn-xs" %>
			  </div>
			<div class="next-btn">
			<%=  f.submit "次へ", class: "btn btn-success btn-lg btn-block", :size => "50*24" %>
			</div>
		<% end %>
  	</div>
  </div>	
</div>

app/views/admin_products/show.html.erb
<div class = "row row-bg">
  <section class = "product-box">
    <div class = "product-menu">
      <h2 class = "page-title">商品詳細</h2>
      <div>
       <%= attachment_image_tag @product, :product_image, size: "300x300", format: 'jpeg', fallback: "no_image.jpg" %>
      </div>
      <div class = "product-favorites">
          <i class="far fa-heart"><%= @product.favorites.count %></i><span class = "favorite-text">いいね</span>
      </div>
      <div class = "product-reviews">
        <i class="far fa-file-alt"><%= @product.reviews.count %>件のレビュー</i>
      </div>
    </div>

    <div class = "product-detail">
      <table class = "table table-bordered table-striped">
        <tr>
          <th>商品ID</th>
          <td class = "product-title"><%= @product.id %></td>
        </tr>
        <tr>
          <th>タイトル</th>
          <td class = "product-title"><%= @product.title %></td>
        </tr>
        <tr>
          <th>アーティスト名</th>
          <td class = "product-title"><%= @product.artist.name %></td>
        </tr>
        <tr>
          <th>レーベル名</th>
          <td class = "product-title"><%= @product.label.name %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td class = "product-title"><%= @product.genre.name %></td>
        </tr>
        <tr>
          <th>構成数</th>
          <td class = "product-title"><%= @product.discs.count %></td>
        </tr>
        <tr>
          <th>収録曲</th>
          <td class = "product-title">
            <% @product.discs.each do |disc| %>
                <ol>ディスク.<%= disc.disc_num %></ol>
              <% disc.songs.each do |song| %>
                <ol><%= song.song_num %>.<%= song.name %></ol>
              <% end %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>

    <div class = "purchase-area">
      <h2><%= @product.sale_status %></h2>
      <h2>在庫数：<%= @stocks %></h2>
      <h2>価格：<%= @product.price %>円(税込)</h2>
      <%= link_to "入荷する", admins_arrival_records_new_path, class: "btn btn-success btn-sm btn-block", style:"margin:5px" %>
      <%= link_to "編集する", admins_products_edit_path(@product), class: "btn btn-success btn-sm btn-block", style:"margin:5px" %>
      <%= link_to "商品一覧に戻る", admins_products_path, class: "btn btn-info btn-sm btn-block", style:"margin:5px" %>
    </div>
  </section>
</div>

<div class = "row row-bg">
  <div class = "review-box">
    <h2 class = "review-title">レビュー一覧</h2>
    <table class = "table table-bordered table-striped review-table">
      <thead>
        <tr>
          <td style = "font-weight: bold">ユーザ名</td>
          <td style = "font-weight: bold">レビュー</td>
        </tr>
      </thead>
      <tbody>
        <% @reviews.each do |review| %>
          <tr>
            <td class = "review-content"><%= link_to review.end_user.first_name, admins_user_path(review.end_user.id) %></td>
            <td class = "review-content"><%= link_to review.review_content, admins_review_edit_path(review) %></td>
          </tr>
        <% end %>
        <div class="page-item">
        <%= paginate @reviews %>
        </div>
      </tbody>
    </table>
  </div>
</div>