config/routes.rb
Rails.application.routes.draw do

  root "products#index"

  # admin

    # adminコントローラ
      get 'admin' =>'admins#index'

    # admin_endusersコントローラ
      get "admins/users" => "admin_endusers#index"
      get "admins/users/:id" => "admin_endusers#show", as: "admins_user"
      get "admins/users/:id/edit" => "admin_endusers#edit", as: "admins_users_edit"
      patch "admins/users/:id" => "admin_endusers#update", as: "admins_users_update"
      delete "admins/users/:id" => "admin_endusers#destroy", as:"admins_users_destroy"

    # admin_productsコントローラ
      get "admins/products/new" => "admin_products#new"
      get "admins/products" => "admin_products#index"
      get "admins/products/:id" => "admin_products#show", as: "admins_product"
      post "admins/products/new" => "admin_products#create", as: "admins_product_create"
      get "admins/products/:id/edit" => "admin_products#edit", as: "admins_products_edit"
      patch "admins/products/:id" => "admin_products#update",as: "admins_products_update"
      put "admins/products/:id" => "admin_products#update"
      delete "admins/products/:id" => "admin_products#destroy"

    # admin_inquiriesコントローラ
      get "admins/inquiries" => "admin_inquiries#index"
      get "admins/inquiries/:id" => "admin_inquiries#show", as: "admins_inquiry"
      # post "admins/inquiries/:id" => "admin_inquiries#create"
      patch "admins/inquiries/:id" => "admin_inquiries#create"

    # admin_reviewsコントローラ
      get "admins/reviews/:id/edit" => "admin_reviews#edit", as: "admins_review_edit"
      patch "admins/reviews/:id" => "admin_reviews#update", as: "admins_review_update"
      put "admins/reviews/:id" => "admin_reviews#update"
      delete "admins/reviews/:id" => "admin_reviews#destroy", as: "admins_review_destroy"

    # admin_order_historiesコントローラ
      get "admins/order_histories" => "admin_order_histories#index"
      get "admins/order_histories/:id" => "admin_order_histories#show", as: "admins_order_history"
      patch "admins/order_histories/:id" => "admin_order_histories#update", as: "admins_order_history_update"
      put "admins/order_histories/:id" => "admin_order_histories#update"

    # admin_arrival_recordsコントローラ
      get "admins/arrival_records" => "admin_arrival_records#index"
      get "admins/:id/arrival_records/new" => "admin_arrival_records#new", as: "admins_arrival_records_new"
      post "admins/:id/arrival_records" => "admin_arrival_records#create", as: "admins_arrival_records_create"

    # admin devise
      devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }


  # end_users

    # usersコントローラ
      get "users/close" => "users#complete"
      get "users/:id" => "users#show", as: "user"
      get "users/:id/edit" => "users#edit",as: "users_edit"
      get "users/:id/close" => "users#close",as: "user_close"
      patch "users/:id" => "users#update",as:"user_update"
      put "users/:id" => "users#update"
      delete "users/:id/destroy" => "users#destroy",as: "destroy_user"

    # user_reviewsコントローラ
      get "product/:id/user_reviews" => "user_reviews#index", as: "product_reviews"
      post "products/:id" => "user_reviews#create"

    # productsコントローラ
      get "products/search" => "products#search"
      resources :products, only:[:show,:create]


    # user_inquiriesコントローラ
      get "user/:id/inquiries/complete" => "user_inquiries#complete", as: "user_inquiries_complete"
      get "user/:id/inquiries/new" => "user_inquiries#new", as: "new_user_inquiry"
      post "user/:id/inquiries" => "user_inquiries#create", as: "user_inquiries"

    # user_cartsコントローラ

      get "carts" => "user_carts#index", as: "user_carts"
      patch "carts/:id" => "user_carts#update",as: "user_carts_update"
      put "carts/:id" => "user_carts#update"
      delete "carts/:id" => "user_carts#destroy",as: "user_carts_delete"
      post "carts/:id" => "user_carts#create" ,as: "user_carts_create"

    # user_purchasesコントローラ
      get "users/:id/purchase/new" => "user_purchases#new", as: "user_purchases_new"
      post "users/:id/purchase" => "user_purchases#create", as: "user_purchases_create"
      get "users/purchase/complete" => "user_purchases#complete"

    # user_addressesコントローラ
      get "users/:id/user_addresses" => "user_addresses#show", as: "user_address"
      get "users/:id/user_addresses/new" => "user_addresses#new", as: "user_addresses_new"
      post "users/:id/user_addresses/new" => "user_addresses#create", as:"user_address_create"
      get "users/:id/user_addresses/edit" => "user_addresses#edit", as: "user_addresses_edit"
      patch "users/:id/user_addresses" => "user_addresses#update", as: "user_addresses_update"
      put "users/:id/user_addresses" => "user_addresses#update"
      delete "users/:id" => "user_addresses#destroy",as: "user_address_destroy" #userのshowページ

    # user_order_historiesコントローラ
      get "users/user_order_histories/:id" => "user_order_histories#show", as: "user_order_history"


    # user_favoritesコントローラ
      post "users/:id/favorites" => "user_favorites#create", as: "user_favorites_create"
      delete "users/:id/favorites" => "user_favorites#destroy", as: "user_favorites_destroy"

    # user_genresコントローラー
      get "/genres/:id" => "user_genres#show", as: "user_genre"

    #end_user devise
      devise_for :end_users, controllers: {
      sessions:      'users/sessions',
      passwords:     'users/passwords',
      registrations: 'users/registrations'
    }





end

app/models/product.rb
class Product < ApplicationRecord

  validates :title            ,presence: true

  validates :price            ,presence: true ,numericality: {greater_than_or_equal_to: 1}

  validates :release_date     ,presence: true


    enum sale_status:{
      販売停止中: 0,
      販売中: 1
    }


  belongs_to :artist
  belongs_to :label
  belongs_to :genre

  has_many :favorites         ,dependent: :destroy
  has_many :reviews           ,dependent: :destroy
  has_many :arrival_records
  has_many :discs			        ,dependent: :destroy
  has_many :carts             ,dependent: :destroy
  has_many :product_histories ,dependent: :destroy

  attachment :product_image
  accepts_nested_attributes_for :discs, allow_destroy: true
  acts_as_paranoid

  scope :search, -> (search_params) do
    return if search_params.blank?

    title_like(search_params[:title])
  end

   scope :title_like, -> (title) { where('title LIKE ?', "%#{title}%") if title.present? }
###いいね機能
   def favorited_by?(end_user)
     favorites.where(end_user_id: end_user.id).exists?
   end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController



  def index
  	 @all_ranks = Product.find(Favorite.group(:product_id)
  	 							.order('count(product_id) desc')
  	 							.limit(5) .pluck(:product_id))

   @user = current_end_user
   @new_products = Product.page(params[:page]).order(release_date: :desc).per(9)
   @genres = Genre.all

  end

  def show
     @product = Product.find(params[:id])
     @reviews = @product.reviews.limit(5)
     @user = current_end_user
     @arrival_stocks = @product.arrival_records.all.sum(:arrival_product)
     @history_stocks = @product.product_histories.all.sum(:order_quantity)
     @stocks = @arrival_stocks - @history_stocks
     @cart = Cart.new
  end

def search
  @user = current_end_user
  @genres = Genre.all
end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="main-content">
	<h1 class = "catch-copy"><br>あなたのCDデビュー<br>お手伝いします!!
</div>
<div class="main">
	<div class="sidenav-flex" style="float: right;">
		<h3>ジャンル</h3>
		<ul>
			<% @genres.each do |genre| %>
			<li>
			  <%= link_to "#{genre.name}(#{genre.products.count})", user_genre_path(genre.id) %>
			</li>
			<% end %>
		</ul>
	</div>
	<div class="ranking">
	  <% if Favorite.exists? %>
		<div>
			<h2>いいね！ランキングTOP5</h2>
		</div>
	  <%end%>
		<div class="ranking-colu">
			<ul>
				<div class="rank-flex">
					<% @all_ranks.each.with_index(1) do |rank,i| %>
					<li class="rank-item">
						<i class="fas fa-compact-disc" aria-hidden="true" style="color:#FF00FF;"></i>
						<span class="rank"><%= "No.#{i}" %></span>
       					<span><%= rank.favorites.count %>いいね！</span>
							<div class="jacket-image">
								<%= attachment_image_tag rank, :product_image,fallback: "no_image.jpg", size: "100x100" %>
							</div>
							<div>
								<h5><%= rank.title %><br></h5>
								<h5><%= rank.artist.name %><br></h5>
								<h5>価格：<%= rank.price %>円(税込)<br></h5>
								<h5><%= link_to "詳細を見る", product_path(rank.id) %></h5>
							</div>
					</li>
					<% end %>
				</div>
			</ul>
		</div>	
	</div>	
	<div class="new">
		<h2>最新作</h2>
		<div class="new-colu">
			<ul>
				<div class="flex">
					<% @new_products.each do |product| %>
						<li class="list">
							<h5><%= product.release_date %>発売</h5>
							<div class="jacket-image">
								<%= attachment_image_tag product, :product_image,fallback: "no_image.jpg", size: "100x100" %>
							</div>
							<div>
								<h5><%= product.title %><br></h5>
								<h5><%= product.artist.name %><br></h5>
								<h5>価格：<%= product.price %>円(税込)<br></h5>
								<h5><%= link_to "詳細を見る", product_path(product.id) %></h5>
							</div>
						</li>
					<% end %>
				</div>
			</ul>
			<div class="page-item">
			<%= paginate @new_products %>
			</div>
		</div>
	</div>
</div>

app/views/products/search.html.erb
<div class="main">
	<div class="container">
		<div class="row">
			<div class="col-lg-2"></div>
				<div class="col-lg-8">
	  			<div>
	  				<h2>検索結果</h2>
	  				<span><%= @product_count %>件のタイトルがヒットしました</span>
	  			</div>
	  			<div>
	  				<div class="new-colu">
	  					<ul>
	  						<% @products.each do |product| %>
	  						<div class="row list-sarch">
	  							<li>
	  							  <h4><%= product.release_date %>発売</h4>
	  							  <div class="jacket-image col-lg-6">
								  	<%= attachment_image_tag product, :product_image,fallback: "no_image.jpg", size: "300x300" %>
								  </div>
									<div class="item-col col-lg-6">
										<h4>タイトル:<%= link_to product.title, product_path(product.id) %><br></h4>
										<h4>レーベル:<%= product.label.name %><br></h4>
										<h4>アーティスト:<%= product.artist.name %><br></h4>
										<h4>ジャンル:<%= link_to product.genre.name, user_genre_path(product.genre.id) %><br></h4>
										<h4>価格：<%= product.price %>円(税込)<br></h4>
										<h4><%= link_to "商品詳細へ",  product_path(product.id) %></h4>
									</div>
								</li>
							</div>
							<% end %>
						</ul>
						<div class="page-item">
						<%= paginate @products %>
						</div>
				　  </div>	
	　		　</div>	

			</div>
			<div class="col-lg-2">
				<div class="sidenav-flex">
					<p>ジャンル</p>
					<ul>
						<% @genres.each do |genre| %>
						<li>
						  <%= link_to "#{genre.name}(#{genre.products.count})", user_genre_path(genre.id) %>
						</li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>	
	

app/views/products/show.html.erb
<div class = "row row-bg">
  <section class = "product-box">
    <div class = "product-menu">
      <h2 class = "page-title">商品詳細</h2>
      <div>
        <%= attachment_image_tag @product, :product_image, size: "250x250", format: 'jpeg', fallback: "no_image.jpg" %>
      </div>
      <div class = "product-favorites">

        <div id="favorites_buttons_<%= @product.id %>">
             <%= render partial: 'user_favorites/favorite', locals: { product: @product} %>
          </div>

      </div>
      <div class = "product-reviews">
        <%= link_to product_reviews_path  do %>
          <i class="far fa-file-alt"><%= @product.reviews.count %>件のレビュー</i>
        <% end %>
      </div>
    </div>

    <div class = "product-detail">
      <table class = "table table-bordered table-striped">
        <tr>
          <th>タイトル</th>
          <td class = "product-title"><%= @product.title %></td>
        </tr>
        <tr>
          <th>アーティスト名</th>
          <td class = "product-title"><%= @product.artist.name %></td>
        </tr>
        <tr>
          <th>レーベル名</th>
          <td class = "product-title"><%= @product.label.name %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td class = "product-title"><%= @product.genre.name %></td>
        </tr>
        <tr>
          <th>構成数</th>
          <td class = "product-title"><%= @product.discs.count %></td>
        </tr>
        <tr>
          <th>収録曲</th>
          <td class = "product-title">
            <% @product.discs.each do |disc| %>
              <ol>ディスク.<%= disc.disc_num %></ol>
              <% disc.songs.each do |song| %>
                <ol><%= song.song_num %>.<%= song.name %></ol>
              <% end %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>

    <div class = "purchase-area">
      <% if @stocks <= 0 %>
        <h2>SOLD OUT !!!!</h2>
      <% elsif end_user_signed_in? && @product.sale_status  == "販売中"%>
        <h2>在庫あり</h2>
          <%= form_for @cart, url: user_carts_create_path do |f| %>
            <%= f.label "数量" %>
            <%= f.number_field :order_quantity , min:1 %>
            <%= f.hidden_field :product_id, :value => @product.id %>
            <%= f.submit "カートに追加する" %>
          <% end %>
      <% elsif end_user_signed_in? && @product.sale_status  == "販売停止中"%>
        <h2>入荷待ち</h2>
      <% elsif admin_signed_in? %>
        <h2><%= @product.sale_status %></h2>
      <% end %>

      <h2>価格</h2>
      <h2><%= @product.price %>円(税込)</h2>

    </div>
  </section>
</div>