config/routes.rb
Rails.application.routes.draw do

  root "products#index"

  # admin

    # adminコントローラ
      get 'admin' =>'admins#index'

    # admin_endusersコントローラ
      get "admins/users" => "admin_endusers#index"
      get "admins/users/:id" => "admin_endusers#show", as: "admins_user"
      get "admins/users/:id/edit" => "admin_endusers#edit", as: "admins_users_edit"
      patch "admins/users/:id" => "admin_endusers#update", as: "admins_users_update"
      delete "admins/users/:id" => "admin_endusers#destroy", as:"admins_users_destroy"

    # admin_productsコントローラ
      get "admins/products/new" => "admin_products#new"
      get "admins/products" => "admin_products#index"
      get "admins/products/:id" => "admin_products#show", as: "admins_product"
      post "admins/products/new" => "admin_products#create", as: "admins_product_create"
      get "admins/products/:id/edit" => "admin_products#edit", as: "admins_products_edit"
      patch "admins/products/:id" => "admin_products#update",as: "admins_products_update"
      put "admins/products/:id" => "admin_products#update"
      delete "admins/products/:id" => "admin_products#destroy"

    # admin_inquiriesコントローラ
      get "admins/inquiries" => "admin_inquiries#index"
      get "admins/inquiries/:id" => "admin_inquiries#show", as: "admins_inquiry"
      # post "admins/inquiries/:id" => "admin_inquiries#create"
      patch "admins/inquiries/:id" => "admin_inquiries#create"

    # admin_reviewsコントローラ
      get "admins/reviews/:id/edit" => "admin_reviews#edit", as: "admins_review_edit"
      patch "admins/reviews/:id" => "admin_reviews#update", as: "admins_review_update"
      put "admins/reviews/:id" => "admin_reviews#update"
      delete "admins/reviews/:id" => "admin_reviews#destroy", as: "admins_review_destroy"

    # admin_order_historiesコントローラ
      get "admins/order_histories" => "admin_order_histories#index"
      get "admins/order_histories/:id" => "admin_order_histories#show", as: "admins_order_history"
      patch "admins/order_histories/:id" => "admin_order_histories#update", as: "admins_order_history_update"
      put "admins/order_histories/:id" => "admin_order_histories#update"

    # admin_arrival_recordsコントローラ
      get "admins/arrival_records" => "admin_arrival_records#index"
      get "admins/:id/arrival_records/new" => "admin_arrival_records#new", as: "admins_arrival_records_new"
      post "admins/:id/arrival_records" => "admin_arrival_records#create", as: "admins_arrival_records_create"

    # admin devise
      devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }


  # end_users

    # usersコントローラ
      get "users/close" => "users#complete"
      get "users/:id" => "users#show", as: "user"
      get "users/:id/edit" => "users#edit",as: "users_edit"
      get "users/:id/close" => "users#close",as: "user_close"
      patch "users/:id" => "users#update",as:"user_update"
      put "users/:id" => "users#update"
      delete "users/:id/destroy" => "users#destroy",as: "destroy_user"

    # user_reviewsコントローラ
      get "product/:id/user_reviews" => "user_reviews#index", as: "product_reviews"
      post "products/:id" => "user_reviews#create"

    # productsコントローラ
      get "products/search" => "products#search"
      resources :products, only:[:show,:create]


    # user_inquiriesコントローラ
      get "user/:id/inquiries/complete" => "user_inquiries#complete", as: "user_inquiries_complete"
      get "user/:id/inquiries/new" => "user_inquiries#new", as: "new_user_inquiry"
      post "user/:id/inquiries" => "user_inquiries#create", as: "user_inquiries"

    # user_cartsコントローラ

      get "carts" => "user_carts#index", as: "user_carts"
      patch "carts/:id" => "user_carts#update",as: "user_carts_update"
      put "carts/:id" => "user_carts#update"
      delete "carts/:id" => "user_carts#destroy",as: "user_carts_delete"
      post "carts/:id" => "user_carts#create" ,as: "user_carts_create"

    # user_purchasesコントローラ
      get "users/:id/purchase/new" => "user_purchases#new", as: "user_purchases_new"
      post "users/:id/purchase" => "user_purchases#create", as: "user_purchases_create"
      get "users/purchase/complete" => "user_purchases#complete"

    # user_addressesコントローラ
      get "users/:id/user_addresses" => "user_addresses#show", as: "user_address"
      get "users/:id/user_addresses/new" => "user_addresses#new", as: "user_addresses_new"
      post "users/:id/user_addresses/new" => "user_addresses#create", as:"user_address_create"
      get "users/:id/user_addresses/edit" => "user_addresses#edit", as: "user_addresses_edit"
      patch "users/:id/user_addresses" => "user_addresses#update", as: "user_addresses_update"
      put "users/:id/user_addresses" => "user_addresses#update"
      delete "users/:id" => "user_addresses#destroy",as: "user_address_destroy" #userのshowページ

    # user_order_historiesコントローラ
      get "users/user_order_histories/:id" => "user_order_histories#show", as: "user_order_history"


    # user_favoritesコントローラ
      post "users/:id/favorites" => "user_favorites#create", as: "user_favorites_create"
      delete "users/:id/favorites" => "user_favorites#destroy", as: "user_favorites_destroy"

    # user_genresコントローラー
      get "/genres/:id" => "user_genres#show", as: "user_genre"

    #end_user devise
      devise_for :end_users, controllers: {
      sessions:      'users/sessions',
      passwords:     'users/passwords',
      registrations: 'users/registrations'
    }





end

app/controllers/user_carts_controller.rb
class UserCartsController < ApplicationController

	before_action :authenticate_end_user!, only:[:index, :update, :destroy, :create]

	def index
	  @user = current_end_user
	end

	def update
      cart = Cart.find(params[:id])
	  cart.update(cart_params)
	  redirect_to user_carts_path
	end

	def destroy
	  @cart = Cart.find(params[:id])
	  @cart.destroy
	  redirect_to user_carts_path
	end

	def create
		@product = Product.find(params[:id])
	    if Cart.where(product_id: params[:id], end_user_id: current_end_user.id).empty?
			@cart = Cart.new(cart_params)
			@cart.product_id = @product.id
			@cart.end_user_id = current_end_user.id
			if @cart.save
				flash[:success] = "カートに追加しました"
				redirect_to user_carts_path 
			else
				flash.now[:danger] = "カートに追加できませんでした"
				render template: 'products/show' 
			end
    	else
		    @cart = Cart.where(product_id: params[:id], end_user_id: current_end_user.id).first
				@cart.update(order_quantity: params[:cart][:order_quantity].to_i + @cart.order_quantity)
				redirect_to user_carts_path
		end
  end


	private

		def cart_params
	  	params.require(:cart).permit(:order_quantity, :end_user_id, :product_id)
		end
end

app/helpers/user_carts_helper.rb
module UserCartsHelper
end

app/views/user_carts/index.html.erb
<!--reference: https://codeday.me/jp/qa/20190309/384838.html -->
<div class = "row cart-box">
	<h1 class = "cart-title">買い物かご</h1>
	<div class="col-xs-9" >
		<section class = "purchase-products-box">
			<div class = "purchase-products-box-inner">
				<% if current_end_user.carts.empty? %>
					<h1 class = "notification">カートに商品が入っていません</h1>
				<% end %>
				<% current_end_user.carts.each do |cart| %>
				<div class = "purchase-product">
					<div class = "purchase-product-image">
						<%= attachment_image_tag cart.product, :product_image, size: "70x70", format: 'jpeg', fallback: "no_image.jpg", class: "purchase-product-img"  %>
					</div>
				        <ul class="purchase-product-name-list">
				      	<strong><%= link_to cart.product.title,product_path(cart.product) %></strong>
				      	<li><%= cart.product.artist.name %></li>
				      	<li><%= cart.product.label.name %></li>
				      	<li><%= cart.product.genre.name %></li>
			        </ul>
				      <p class="purchase-product-price">小計:&yen;<%= cart.product.price*cart.order_quantity %>(税込)</p>
				    <div class = "purchase-product-option">
				    	<%= form_for cart, url: user_carts_update_path(cart) do |f| %>
						<%= f.number_field :order_quantity ,min:1 %>
						<p><%= f.submit "個数を変更する" %></p>
						<% end %>
						<div class="purchase-product-option-delete">
							<%= link_to '削除',user_carts_delete_path(cart.id), class: "btn-sm btn-danger ", method: :delete %>
						</div>
					</div>
			  	</div>
			  	<% end %>
		  	</div>
		</section>
	</div>



	<div class="col-xs-3">
		<section class = "purchase-box">
			<div class="purchase-box-inner">
				<% total_price = current_end_user.carts.inject(0){|sum,cart| sum + cart.product.price*cart.order_quantity} %>
				<h3 class="total-price">合計:&yen;<%= total_price %></h3>
				<% if current_end_user.carts.exists? %>
				<div class = "purchase-button">
					<%= link_to '購入手続きへ',user_purchases_new_path(current_end_user), class: "btn-lg btn-warning " %>
					<% end %>
				</div>
				<div class = "product-show-link">
					<%= link_to '商品一覧ページへ',root_path %>
				</div>
			</div>
		</section>
	</div>
</div>